# Generated by Django 5.2.9 on 2025-12-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpaceWeatherLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("metric", models.CharField(max_length=50)),
                ("value", models.FloatField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [models.Index(fields=["timestamp", "metric"], name="astronomy_s_timesta_7f047e_idx")],
                "unique_together": {("timestamp", "metric")},
            },
        ),
    ]
