# Generated by Django 5.2.9 on 2026-01-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EconomicIndicator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "country_iso3",
                    models.CharField(
                        choices=[
                            ("USA", "United States"),
                            ("JPN", "Japan"),
                            ("CHN", "China"),
                            ("IND", "India"),
                            ("DEU", "Germany"),
                            ("GBR", "United Kingdom"),
                            ("FRA", "France"),
                            ("CAN", "Canada"),
                            ("AUS", "Australia"),
                        ],
                        db_index=True,
                        max_length=3,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "indicator_type",
                    models.CharField(
                        choices=[
                            ("STOCK", "Stock Index"),
                            ("GDP", "GDP (Constant 2015 US$)"),
                            ("INFLATION", "Inflation (CPI %)"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("value", models.FloatField(null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["country_iso3", "indicator_type", "date"], name="economy_eco_country_240e3a_idx"
                    )
                ],
                "unique_together": {("country_iso3", "date", "indicator_type")},
            },
        ),
    ]
