# Generated by Django 5.2.9 on 2026-01-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Earthquake",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("usgs_id", models.CharField(help_text="USGS Event ID", max_length=50, unique=True)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("magnitude", models.FloatField()),
                ("place", models.CharField(max_length=255)),
                ("depth", models.FloatField(help_text="Depth in km")),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Earthquake",
                "verbose_name_plural": "Earthquakes",
                "ordering": ["-timestamp"],
                "indexes": [models.Index(fields=["timestamp", "magnitude"], name="geology_ear_timesta_7d0ca7_idx")],
            },
        ),
    ]
